kind: pipeline
type: docker
name: drone-agents-poweron

clone:
  disable: true

steps:
- name: drone-agents-poweron
  image: walkero/hcloud:1.30
  environment:
    HCLOUD_TOKEN:
      from_secret: HCLOUD_TOKEN
  commands:
    - hcloud server poweron drone-agents

trigger:
  branch:
    include:
    - master
    - develop
  event:
    include:
    - push
    - pull_request
    - tag

---

kind: pipeline
type: docker
name: compile-jsc

workspace:
  path: /drone/src

steps:
- name: with-clib2
  pull: always
  image: walkero/webkitondocker
  commands:
  - make -f Makefile jscore-amigaos

trigger:
  branch:
    include:
    - amigaos_*
    - ci-cd
  event:
    include:
    - push
    - pull_request

depends_on:
  - drone-agents-poweron

node:
  agents: builders

---

kind: pipeline
type: docker
name: drone-agents-poweroff

clone:
  disable: true

steps:
- name: drone-agents-poweroff
  image: walkero/hcloud:1.30
  environment:
    HCLOUD_TOKEN:
      from_secret: HCLOUD_TOKEN
  commands:
    - curl -sw "\n" "http://10.0.0.2:5000/container/count/drone-" | while read var1; do if [ $var1 -eq 1 ]; then hcloud server poweroff drone-agents; fi ; done

depends_on:
  - compile-tests
  - compile-release-bytag

trigger:
  status:
    - failure
    - success
  branch:
    include:
    - master
    - develop
  event:
    include:
    - push
    - pull_request
    - tag
