kind: pipeline
type: docker
name: compile-jsc

clone:
  depth: 1

workspace:
  path: /opt/code/webkitty

steps:
- name: with-clib2
  pull: always
  image: walkero/webkitondocker
  commands:
  - make Dummy/libdummy.a
  - cp Dummy/libdl.a /opt/sdk/ppc-amigaos/local/clib2/lib/
  - make -f Makefile jscore-amigaos

trigger:
  branch:
    include:
    - amigaos_*
    - ci-cd-aws
  event:
    include:
    - push
    - pull_request

node:
  agents: awsbuilders
