kind: pipeline
type: docker
name: awsbuilders-poweron

clone:
  disable: true

steps:
- name: start-aws-instances
  pull: always
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - aws ec2 start-instances --region eu-north-1 --instance-ids i-01e3d598710a23947

trigger:
  branch:
    include:
    - amigaos_*
  event:
    include:
    - pull_request
    - merge

---

kind: pipeline
type: docker
name: compile-jsc

clone:
  depth: 1

workspace:
  path: /opt/code/webkitty

steps:
- name: with-clib2
  pull: always
  image: walkero/webkitondocker
  commands:
  - make Dummy/libdummy.a
  - cp Dummy/libdl.a /opt/sdk/ppc-amigaos/local/clib2/lib/
  - make jscore-amigaos

trigger:
  branch:
    include:
    - amigaos_*
  event:
    include:
    - pull_request
    - merge

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders
