labels:
  role: awsbuilder
  platform: linux/amd64

workspace:
  path: /opt/code/webkitty

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 1

steps:
  - name: build-minibrowser
    image: walkero/webkitondocker
    commands:
    - make Dummy/libdummy.a
    - cp Dummy/libdl.a /opt/ppc-amigaos/ppc-amigaos/SDK/local/clib4/lib/
    - make .build-mini USE_CLIB4=YES

when:
  - branch: amigaos_2.36.8
    event: [push]

depends_on:
  - aws-poweron